### ISSUE TITLE
[PORT] Updated MicrosoftGovernmentAppCredentials to support Skills in Azure Gov

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-java#264]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3353

Fixes https://github.com/microsoft/botbuilder-dotnet/issues/3233

Added constructor to MicrosoftGovernmentAppCredentials that takes OAuthScope to support skills in gov.
Updated BotFrameworkHttpClient and BotFrameworkAdapter to pass the OAuthScope to MicrosoftGovernmentAppCredentials
Added SimpleBotToBot functional test for testing.
Added Microsoft.Bot.Framework.Skills.sln to load skills test projects.

# Changed projects
* Microsoft.Bot.Builder
* Microsoft.Bot.Connector
* integration
* Microsoft.Bot.Connector.Tests

[Skills]

**Comment by gabog** [comment]
Hi @tracyboehrer, does it make sense to keep this one open? Or should we just close it and we'll address it implicitly when we support skills in java?

**Comment by tracyboehrer** [comment]
@gabog I'm not so sure this doesn't fall just as much into Area: Authentication.  I notice some differences in the various AppCredentials classes.  Generally, I close Skills related issues if I am sure they would be covered when Skills are added to Java.  But I'm not sure this is the case here. As in, would it be possible to implement Skills, and easily overlook this change?

**Comment by gabog** [comment]
I am working on a draft spec for skill functional testing, once we support skills, we should add Java to the [testing matrix](https://github.com/microsoft/botframework-sdk/blob/gabog/skillsSpecUpdates/specs/testing/skills/SkillsFunctionalTesting.md#1-single-turn-interaction-with-a-skill) and this issue will come up because we needs to test skills support on all 3 auth environments. 

I'll flag this as backlog for now, you can close it if it causes too much noise (we will find out we miss this change once we run the test matrix).

**Comment by tracyboehrer** [comment]
Depends on #738
