### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botbuilder-java#81]
Every network call should use proxy settings if they are present.

[enhancement]

**Comment by tracyboehrer** [comment]
One strategy employed by dotnet was to allow for a custom HttpClient.  I am hesitant to do the same in Java since not only does this expose implementation details that could change, it also requires for more than the HttpClient.  In Java, this functionality is fulfilled by the MS RestClient, which includes a http client and a REST client (retrofit).  

As a work-around for now, I supplied ConnectorClientImpl.getDefaultRestClientBuilder to provide the same Builder we use internally, and proxy and proxy auth information can be added on.  The resulting RestClient can be passed to ConnectorClientImpl on construction.

Long term, proxy and proxy auth settings should be supplied via app settings.  But the use of MS RestClient has to be resolved first.

**Comment by tracyboehrer** [comment]
Using the Java proxy properties appears to work for an all-or-nothing approach.  This is likely appropriate for a bot.

Example, supply them at the command line:
-Dhttp.proxyHost=localhost -Dhttp.proxyPort=8888 -Dhttps.proxyHost=localhost -Dhttps.proxyPort=8888

For an Azure deployment, these would be specified in the JAVA_OPTS under "Application Settings" for the App Service.

**Comment by EricDahlvang** [comment]
Very cool!  I wish it were this easy in the other languages too.
