### ISSUE TITLE
Java DevOps Pipelines

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/botbuilder-java#833]
Before the GA Java for Build 2021 (mid May 2021), we need DevOps pipelines setup for parity with other repo pipelines:

- [x] Daily
- [x] PR
- [ ] Release (publish to Sonatype)

**Comment by BruceHaley** [comment]
[Daily](https://fuselabs.visualstudio.com/SDK_v4/_build/index?definitionId=365) is running. Also [daily pushes to MyGet](https://fuselabs.visualstudio.com/SDK_v4/_release?definitionId=71).
[CI-PR](https://fuselabs.visualstudio.com/SDK_v4/_build?definitionId=616) is running. No required build checks are set up in GitHub.
Publish to MyGet is running. Skeleton [experimental publish to Sonatype](https://fuselabs.visualstudio.com/SDK_v4/_release?definitionId=72) using the same pattern is set up.

**Comment by BruceHaley** [comment]
Update:
The Daily, when run against the main branch, automatically pushes to the MyGet and the ConversationalAI feeds. For other branches, pushes must be queued manually.

[[experimental]Push-BotBuilder-Java-to-Central](https://fuselabs.visualstudio.com/SDK_v4/_release?_a=releases&view=all&definitionId=133), set up to push to Sonatype, may or may not work. I did not test this because no release version was available to publish. If it fails, you may want first to try tweaking the TargetFeedUrl variable in the release pipeline definition.

Re yaml: The build and release pipelines are currently in classic format. Release pipelines in yaml format are not supported. The build pipelines have a yaml generator in the UI that can automatically duplicate the pipelines in yaml file format. The advantage of classic is that pipeline prototyping and modification is easier and faster than working in yaml. Some of our products are still in classic. I suggest you leave the Java build pipelines in classic format for a while until your operation is fully operational and stabilized. Then if desired they can be converted to yaml at your leisure.
