### ISSUE TITLE
Add quickstart steps for installation via POM file dependency

### ISSUE THREAD

**Issue by jpblair** [microsoft/botbuilder-java#943]
The docs only include steps to build the library locally, but not on how to download it from Maven Central via a POM file dependency. From what I can tell, [this](https://mvnrepository.com/artifact/com.microsoft.bot/bot-builder) set of packages is the correct one, but I'm hesitant to import it until official documentation confirms that it is legitimate.

In particular, I'd like to verify the authenticity of [this package](https://mvnrepository.com/artifact/com.microsoft.bot/bot-builder).

**Comment by tracyboehrer** [comment]
@jpblair Since Java is still in preview, the samples are setup using the same package version as the libraries, which means it only works if you do a "mvn install", then build your sample.

If you want to modify the POM for a sample to use a released packages from Maven, then "4.6.0-preview7" is the version you'd need.

When Java is GA in mid-May, this won't be the case as the Samples will be relocated to the botframework-sample GitHub repo with the other samples, and build against released packages on Maven.

**Comment by tracyboehrer** [comment]
@jpblair Please note that using the released packages on Maven won't work for every sample though.  For example, any sample that uses the bot-dialogs package requires 4.6.0-preview8, which is what is in the main branch (not released on Maven yet).

**Comment by jpblair** [comment]
@tracyboehrer Thanks for the reply. To be clear, I'm not looking to run the samples. I just want to use the Maven-released version of the packages (with the understanding that they are not GA yet), so I was looking to confirm that the link I provided in my original post is legitimate and from Microsoft.
